[tool.poetry]
name = "front"
version = "0.1.0"
description = ""
authors = ["Snake <71287573+Nassim667@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.36.0"
pymongo = "^4.8.0"
python-dotenv = "^1.0.1"
<<<<<<< HEAD
matplotlib = "^3.9.1"
seaborn = "^0.13.2"
=======
>>>>>>> develop


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
